/* Yalnızca yeni/boş B2B veritabanında çalıştırın. */

CREATE TABLE B2B_USERS (
    ID CHAR(36) NOT NULL,
    EMAIL VARCHAR(254) NOT NULL,
    DISPLAY_NAME VARCHAR(160) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_B2B_USERS PRIMARY KEY (ID),
    CONSTRAINT UQ_B2B_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE B2B_USER_CARI_ACCESS (
    USER_ID CHAR(36) NOT NULL,
    CARI_NO BIGINT NOT NULL,
    IS_DEFAULT BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT PK_B2B_USER_CARI_ACCESS PRIMARY KEY (USER_ID, CARI_NO),
    CONSTRAINT FK_B2B_USER_CARI_USER FOREIGN KEY (USER_ID) REFERENCES B2B_USERS (ID)
);

CREATE TABLE B2B_CARTS (
    ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    CARI_NO BIGINT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_B2B_CARTS PRIMARY KEY (ID),
    CONSTRAINT FK_B2B_CART_USER FOREIGN KEY (USER_ID) REFERENCES B2B_USERS (ID)
);

CREATE TABLE B2B_CART_LINES (
    ID CHAR(36) NOT NULL,
    CART_ID CHAR(36) NOT NULL,
    STOK_NO BIGINT NOT NULL,
    VARIANT_KEY VARCHAR(160),
    QUANTITY DECIMAL(18, 4) NOT NULL,
    CONSTRAINT PK_B2B_CART_LINES PRIMARY KEY (ID),
    CONSTRAINT FK_B2B_CART_LINE_CART FOREIGN KEY (CART_ID) REFERENCES B2B_CARTS (ID),
    CONSTRAINT CK_B2B_CART_LINE_QUANTITY CHECK (QUANTITY > 0)
);

